language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: true
node_js:
  - v5
before_script:
  - npm install -g gulp
  - npm install
script:
  gulp test
notifications:
  email: false
